from .usuario import Usuario
from .rol import Rol
from .ficha import Ficha
from .coordinacion import Coordinacion
from .competencia import Competencia
from .proyecto import Proyecto
from .programa import Programa
from .materiales import Material
from .nota import Nota
